const numberOfSvg = 60;
var svgFiles = [
    'about.svg',		     'bad_decision.svg',	   'callback.svg',
    'accept_database.svg',	     'bar_chart.svg',	   'camcorder.svg',
    'add_column.svg',		    'bbc.svg',		   'camcorder_pro.svg',
    'add_database.svg',	     'bearish.svg',	   'camera.svg',
    'add_image.svg',		     'binoculars.svg',	   'camera_addon.svg',
    'add_row.svg',		     'biohazard.svg',	   'camera_identification.svg',
    'address_book.svg',	     'biomass.svg',	   'cancel.svg',
    'advance.svg',	     'biotech.svg',	   'candle_sticks.svg',
    'advertising.svg',	     'bookmark.svg',	   'capacitor.svg',
    'alarm_clock.svg',		     'briefcase.svg',	   'cd_logo.svg',
    'alphabetical_sorting_az.svg',  'broken_link.svg',	   'cell_phone.svg',
    'alphabetical_sorting_za.svg',  'bullish.svg',	   'charge_battery.svg',
    'android_os.svg',		     'business.svg',	   'checkmark.svg',
    'answers.svg',		     'business_contact.svg',  'circuit.svg',
    'approval.svg',		     'businessman.svg',	   'clapperboard.svg',
    'approve.svg',		     'businesswoman.svg',	   'clear_filters.svg',
    'area_chart.svg',		     'butting_in.svg',	   'clock.svg',
    'assistant.svg',		     'cable_release.svg',	   'close_up_mode.svg',
    'audio_file.svg',		     'calculator.svg',	 
    'automatic.svg',		     'calendar.svg',
    'automotive.svg',		     'call_transfer.svg',
];